### ISSUE TITLE
Merge blacklists into a single configuration file

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#30]
Ideally we'd like to blacklist scans and subjects from any point in the `run.sh` pipeline, so we're faced with creating a "blacklist" of sorts for each stage. Alternatively, we could create a single configuration file that holds the scans and subjects to ignore, along with a description of why. 

For example: 
```yaml
# metadata/pipelines.yaml
---
ignore: 
  xnat-extract:
    DTI_CMH_H002_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_H014_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_H015_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_H017_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_H028_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_S029_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_S029_01_01_DTI60_01_description: > 
      Okay, this is an interesting one. The subject's data has been acquired 
      successfully, we think, but the dicom headers aren't complete or have 
      been corrupted so every export program we've used fails. We're ignoring
      this data for now then. 
    DTI_CMH_S015_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_S017_01_01_DTI60_01_description: wrong protocol
    DTI_CMH_S028_01_01_DTI60_01_description: wrong protocol
  dtifit: 
    DTI_CMH_H001_01_01_DTI60_01_description: bad contrast
  imob: 
    DTI_CMH_H001_01_01: bad timing information, excluding the scan
```

More verbosely, we could include an author, date, etc.. like so: 

```yaml
ignore: 
  xnat-extract:
    # max structured:
    DTI_CMH_H002_01_01_DTI60_01_description: 
      reason: wrong protocol
      author: @pipitone
      date: 2015-09-17
    # semi-structured
    DTI_CMH_H002_01_01_DTI60_01_description: wrong protocol (@pipitone 2015-09-17)
```
